### ISSUE TITLE
Modpack Inclusion 

### ISSUE THREAD

**Issue by LiviiYS** [Kirilliriks/Bedrodium#1]
Would I be able to get permission to add this to a Modpack uploaded to curseforge?

Allowed to add to curseforge 3rd party approved mods?

**Comment by Kirilliriks** [comment]
> Would I be able to get permission to add this to a Modpack uploaded to curseforge?
> 
> Allowed to add to curseforge 3rd party approved mods?
Of course, I have nothing against my modification being used in a modpack, I give permission for this.

**Comment by Kirilliriks** [comment]
> Would I be able to get permission to add this to a Modpack uploaded to curseforge?
> 
> Allowed to add to curseforge 3rd party approved mods?

Of course, I have nothing against my modification being used in a modpack, I give permission for this.

**Comment by Kirilliriks** [comment]
It will also be cool if you give me the link to the modpack.

**Comment by LiviiYS** [comment]
Running it on my Modpack server


https://www.curseforge.com/minecraft/modpacks/euphoriccuriosity

(My Modpack btw)

**Comment by Kirilliriks** [comment]
> Running it on my Modpack server
> 
> https://www.curseforge.com/minecraft/modpacks/euphoriccuriosity
> 
> (My Modpack btw)

Thanks for the link, it will be interesting to see Bedrodium in modpack.
