### ISSUE TITLE
Nether top bedrock?

### ISSUE THREAD

**Issue by Kasualix** [Kirilliriks/Bedrodium#11]
Currently the optimization is only valid for bedrocks in the dim bottom, how about making it valid for nether-like dim's top?

**Comment by Kirilliriks** [comment]
@Kasualix Good idea, I'll try to implement such a mechanism, but I'm afraid that it should be made only optional. Because the space above the upper plane of the nether world can be built up

**Comment by Kasualix** [comment]
https://github.com/Kirilliriks/Bedrodium/blob/782f572d7d0b7d98b9ef22a2466a9b9fbae2544d/src/main/java/me/kirillirik/bedrodium/Bedrodium.java#L33
btw I would suggest a CLIENT.worldRenderer.reload() after this line to make the effect of this switch more clear , and in this way players don't have to press another keybind to reload the renderer.
