### ISSUE TITLE
Bedrodium 0.2.2 not compitable in 1.20

### ISSUE THREAD

**Issue by HeadyHalilEfe** [Kirilliriks/Bedrodium#14]
![Ekran görüntüsü 2023-12-30 091351](https://github.com/Kirilliriks/Bedrodium/assets/89427306/858c214c-eb71-48e9-871f-0f9c8857b375)
Not compitable on 1.20

**Comment by HeadyHalilEfe** [comment]
![image](https://github.com/Kirilliriks/Bedrodium/assets/89427306/f6d8fb6b-6ce3-499e-abec-5aa3bc64e12b)

**Comment by Kirilliriks** [comment]
@HeadyHalilEfe Thank you for finding this error, I will correct it in the description. Indeed, there is no support for 1.20 in version 2.2
