### ISSUE TITLE
Is This mod required with the existing advanced rejection functions?

### ISSUE THREAD

**Issue by xboct02** [Kirilliriks/Bedrodium#17]
The sodium is full of optimizations, which include the rejection of invisible faces of blocks, which applies to all blocks, including the bedrock. Please specify if this mod brings performance improvements?

**Comment by Kirilliriks** [comment]
> The sodium is full of optimizations, which include the rejection of invisible faces of blocks, which applies to all blocks, including the bedrock. Please specify if this mod brings performance improvements?

No serious tests have been done, the only information available is Feedback from a user who has had his performance boosted by the mod.

To be honest I don't know if Sodium includes the same optimization as Bedrodium mod.

**Comment by xboct02** [comment]
I can only give it to you
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/799

**Comment by Kirilliriks** [comment]
> I can only give it to you [ValkyrienSkies/Valkyrien-Skies-2#799](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/799)

Thanks for the link, I looked into it, the Bedrodium mod has a different method for rejecting polygons.

**Comment by xboct02** [comment]
What does the block face culling option do in the sodium settings?
ChatGPT
The "Block Face Culling" option in the settings of Sodium (an optimization mod for Minecraft) controls the process of filtering out the faces of blocks that are not visible to the player. This process is called "culling" and is aimed at improving rendering performance.

Detailed explanation:
Block Face Culling:

Functionality: This option enables or disables the rendering of those faces of blocks that are not visible to the player. For example, if one side of a block is completely covered by another block, that side will not be rendered.
The goal is to reduce the number of polygons that need to be drawn. This reduces the load on the graphics processor (GPU), which can significantly improve the performance of the game, especially on weak computers.
Examples:
Enabled: If this option is enabled, Minecraft will not draw the faces of blocks that are not visible to the player. For example, the inner sides of the blocks in the wall, hidden by other blocks, will not be rendered.
Disabled: If

**Comment by Kirilliriks** [comment]
> What does the block face culling option do in the sodium settings? ChatGPT The "Block Face Culling" option in the settings of Sodium (an optimization mod for Minecraft) controls the process of filtering out the faces of blocks that are not visible to the player. This process is called "culling" and is aimed at improving rendering performance.
> 
> Detailed explanation: Block Face Culling:
> 
> Functionality: This option enables or disables the rendering of those faces of blocks that are not visible to the player. For example, if one side of a block is completely covered by another block, that side will not be rendered. The goal is to reduce the number of polygons that need to be drawn. This reduces the load on the graphics processor (GPU), which can significantly improve the performance of the game, especially on weak computers. Examples: Enabled: If this option is enabled, Minecraft will not draw the faces of blocks that are not visible to the player. For example, the inner sides of the blocks in the wall, hidden by other blocks, will not be rendered. Disabled: If

Thank you for sharing your research on the issue, in the classical sense of the method that you described removes invisible to the player polygons only BETWEEN blocks, the polygons of the lower layer of the hip will not be discarded by such an algorithm, mod Berdodium just and performs this task. When developing the mod, I did not check whether Sodium includes such optimization, if not, it can be included inside Sodium. I can say that I developed the mod more for studying Fabric and Mixins and did not pursue the goal of an actual and necessary mod, so I specified in the description of the modification that I do not give any guarantees on the correct performance of the mod, all I can say is that theoretically the mod at least loads a smaller number of polygons in the memory of the video card.

Translated with DeepL.com (free version)

**Comment by xboct02** [comment]
If the mod does not load the lower edge of the thigh, then why can I see it when I fly under the world? If it works digamically, then block face culling works similarly with all blocks.

**Comment by xboct02** [comment]
The description indicates that ALL invisible faces of the blocks are ignored.

**Comment by Kirilliriks** [comment]
> If the mod does not load the lower edge of the thigh, then why can I see it when I fly under the world? If it works digamically, then block face culling works similarly with all blocks.

In the first versions of the mod the bottom bedrock layer was really not visible, but VidTu has contributed and added an algorithm that checks if the player is below the bedrock layer and if he is below, his bottom layer starts rendering for the observer.

Check #13

**Comment by xboct02** [comment]
С вами бесполезно спорить

**Comment by Kirilliriks** [comment]
> С вами бесполезно спорить

EN: I'm sorry I couldn't help you.
RU: Мне жаль что не смог помочь вам, если есть желание то можете найти у меня в профиле ссылку на телеграмм аккаунт где я подробнее могу ответить на ваши вопросы.
