### ISSUE TITLE
Mods don't adapt to depth layer

### ISSUE THREAD

**Issue by Foufou10** [Kirilliriks/Bedrodium#3]
So, the mods isn't very compatible with the fact you can change the MC depth limit now (I have the datapack Mojang gave).
A support like a config file (if you want the easy way) or something like your mods automatically detecting the lowest layer (the hard way I guess) could be interesting.

**Comment by Kirilliriks** [comment]
Indeed, the mod counts for the last layer - 0th. Thanks for your comment, I will try to solve this problem.

**Comment by Kirilliriks** [comment]
> So, the mods isn't very compatible with the fact you can change the MC depth limit now (I have the datapack Mojang gave).
> A support like a config file (if you want the easy way) or something like your mods automatically detecting the lowest layer (the hard way I guess) could be interesting.


I will be grateful if you share with me the link / name of the mod that changes the height.

**Comment by griffin4cats** [comment]
The one I mentioned in the invalid github [here](https://github.com/Kirilliriks/BoosterCore/issues/2) is [Nullscape](https://www.planetminecraft.com/data-pack/nullscape/). It's not a mod though, it's a datapack. It changes world height in the End dimension.

**Comment by Foufou10** [comment]
> > So, the mods isn't very compatible with the fact you can change the MC depth limit now (I have the datapack Mojang gave).
> > A support like a config file (if you want the easy way) or something like your mods automatically detecting the lowest layer (the hard way I guess) could be interesting.
> 
> I will be grateful if you share with me the link / name of the mod that changes the height.

I mean, it's just Mojang's datapack. https://feedback.minecraft.net/hc/en-us/articles/4402614709389-Caves-Cliffs-Prototype-Data-Pack-for-Minecraft-Java-Edition

**Comment by griffin4cats** [comment]
Another datapack that doesn't work with it is the Far End datapack I'm testing now
https://www.planetminecraft.com/data-pack/far-end-ender-expansion-datapack-v0-1/

**Comment by Kirilliriks** [comment]
> Another datapack that doesn't work with it is the Far End datapack I'm testing now
> https://www.planetminecraft.com/data-pack/far-end-ender-expansion-datapack-v0-1/
> 
> It's really just any datapack or mod that adds stuff below y = 0

Understood thanks. As soon as free time appears, I will try to figure it out.

**Comment by Kirilliriks** [comment]
@Foufou10 
I am happy to inform you that I have updated the mod, now it supports versions from 1.17 to 1.18 inclusive and supports dynamic height.
