### ISSUE TITLE
1.19? 

### ISSUE THREAD

**Issue by Mangoiz** [Kirilliriks/Bedrodium#6]
I'm getting about 50 FPS more using this mod and 1.19 support would be nice.

**Comment by Kirilliriks** [comment]
@Mangoiz Sorry for the long answer, it's nice to hear that my work improves the performance of the game, I will try to update the mod to 1.19 in the near future and be sure to let you know here. You can also try using version 1.18 for 1.19, it seems to work well, but I have not personally tested it.

**Comment by Kirilliriks** [comment]
> I'm getting about 50 FPS more using this mod and 1.19 support would be nice.

I'm sorry it didn't happen sooner, but I added full support for 1.19.2

**Comment by Mangoiz** [comment]
> I'm sorry it didn't happen sooner, but I added full support for 1.19.2

Lovely, amazing work as always.
