### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by TanCY1** [Kirilliriks/Bedrodium#8]

**Comment by MrRagtime** [comment]
This mod runs fine on **1.19.3**.

**Comment by Aces-and-Jacks** [comment]
well could it be marked on modrinth if it can run on 1.19.3?

**Comment by Kirilliriks** [comment]
@TanCY1 @MrRagtime @Aces-and-Jacks There is a lot of work at the moment, I will try to check this moment in my free time, thanks for your attention!

**Comment by Kirilliriks** [comment]
Отметил это на Modrinth
